### PR TITLE
SDB-8141: fix incorrect assert in EquiJoinSettings.h

### PR DESCRIPTION
**Pull request by jmcq-p4**
_ Fix description: fix incorrect inquality in assert
    in EquiJoinSettings.h from PR #24
_ New tests added to harness: N
_ Schema and storage format changes: N
_ Regression tests executed: checkin
_ User or admin-visible changes: None
_ Reviewed by: jlevine

### CODE REVIEW

**Review by jlevine-p4 — APPROVED** [review]
It works now, thanks!

**Comment by jmcq-p4** [comment]
So are you  going to approve this, please?  (even though not required, I did request it).

**Comment by jlevine-p4** [comment]
I did approve it?

**Comment by jmcq-p4** [comment]
there was no check mark before, but now there is.  Maybe the page was stale.  Thankyou!

**Pull request merged**
